spring:
  application:
    name: soraka-admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soraka?useUnicode=true&characterEncoding=utf8
    username: root
    password: ding135260.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
server:
  port: 8003
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    com.adc.da.system.dao: DEBUG

#为了保护内部服务
security:
  basic:
    enabled: true
  user:
    name: sunbufu
    password: 123456

